### ISSUE TITLE
关于“翻录”功能的疑问

### ISSUE THREAD

**Issue by Aces2017** [kuretru/PyCeleX5#2]
您好，想询问一下，“翻录bin”功能指的是？是否有开源的通过python控制celex相机开始录制和结束录制bin文件的脚本呢？谢谢！

**Comment by kuretru** [comment]
`翻录bin`指：将录制好的bin文件通过集成帧的方式输出为图片，或直接输出为csv文件

**Comment by Aces2017** [comment]
> `翻录bin`指：将录制好的bin文件通过集成帧的方式输出为图片，或直接输出为csv文件

谢谢回复！您是否研究过基于python控制的celex相机event intensity mode等模式下，如何控制相机录制事件流数据？

**Comment by kuretru** [comment]
```python
self.device = PyCeleX5.PyCeleX5()
self.device.openSensor(PyCeleX5.DeviceType.CeleX5_MIPI)
self.device.isSensorReady()
self.device.getClockRate()
self.device.getEventFrameTime()
self.device.getOpticalFlowFrameTime()
self.device.getThreshold()
self.device.getBrightness()
self.device.getEventDataFormat()

# self.device.setRotateType(2)
# self.device.enableFrameDenoising()
# self.device.setThreshold(70)
self.device.setSensorFixedMode(PyCeleX5.CeleX5Mode.Event_Off_Pixel_Timestamp_Mode)

# self.event_dev.setPictureNumber(1, PyCeleX5.CeleX5Mode.Full_Picture_Mode)
# self.event_dev.setEventDuration(20, PyCeleX5.CeleX5Mode.Event_Off_Pixel_Timestamp_Mode)
# self.device.setSensorLoopMode(PyCeleX5.CeleX5Mode.Event_Off_Pixel_Timestamp_Mode, 1)
# self.device.setSensorLoopMode(PyCeleX5.CeleX5Mode.Full_Picture_Mode, 2)
# self.device.setSensorLoopMode(PyCeleX5.CeleX5Mode.Event_Off_Pixel_Timestamp_Mode, 3)
# self.device.setLoopModeEnabled(True)

self.device.setFpnFile(fpn_path)

self.device.startRecording(data_path)

# recoding

self.device.stopRecording()
```

**Comment by Aces2017** [comment]
Thanks a lot!
















At 2022-11-08 14:44:55, "呉真" ***@***.***> wrote:

self.device=PyCeleX5.PyCeleX5()
self.device.openSensor(PyCeleX5.DeviceType.CeleX5_MIPI)
self.device.isSensorReady()
self.device.getClockRate()
self.device.getEventFrameTime()
self.device.getOpticalFlowFrameTime()
self.device.getThreshold()
self.device.getBrightness()
self.device.getEventDataFormat()

# self.device.setRotateType(2)# self.device.enableFrameDenoising()# self.device.setThreshold(70)self.device.setSensorFixedMode(PyCeleX5.CeleX5Mode.Event_Off_Pixel_Timestamp_Mode)

# self.event_dev.setPictureNumber(1, PyCeleX5.CeleX5Mode.Full_Picture_Mode)# self.event_dev.setEventDuration(20, PyCeleX5.CeleX5Mode.Event_Off_Pixel_Timestamp_Mode)# self.device.setSensorLoopMode(PyCeleX5.CeleX5Mode.Event_Off_Pixel_Timestamp_Mode, 1)# self.device.setSensorLoopMode(PyCeleX5.CeleX5Mode.Full_Picture_Mode, 2)# self.device.setSensorLoopMode(PyCeleX5.CeleX5Mode.Event_Off_Pixel_Timestamp_Mode, 3)# self.device.setLoopModeEnabled(True)self.device.setFpnFile(fpn_path)

self.device.startRecording(data_path)

# recodingself.device.stopRecording()

**Comment by Aces2017** [comment]
您好，请问利用python封装C++时，”from build import PyCeleX5“ 报错，指的是需要在新建路径build下，编译运行什么来生成.so文件吗？
