### ISSUE TITLE
关于PyCeleX5进行事件流bin文件录制的疑问

### ISSUE THREAD

**Issue by Aces2017** [kuretru/PyCeleX5#3]
您好，希望实现通过python控制CeleX-MIPI相机每间隔10s采集一次事件流数据，并存为bin文件，但无论是否使用stopRecording()命令，都会存在如下报错：

PyCeleX5.stopRecording(): called
PyCeleX5.stopRippingBinFile(): already stop ripping bin file
LIBUSB_TRANSFER_CANCELLED
LIBUSB_TRANSFER_CANCELLED
LIBUSB_TRANSFER_CANCELLED
LIBUSB_TRANSFER_CANCELLED
LIBUSB_TRANSFER_CANCELLED
LIBUSB_TRANSFER_CANCELLED
LIBUSB_TRANSFER_CANCELLED
LIBUSB_TRANSFER_CANCELLED
LIBUSB_TRANSFER_CANCELLED
LIBUSB_TRANSFER_CANCELLED
LIBUSB_TRANSFER_CANCELLED
stop thread!
LIBUSB_TRANSFER_CANCELLED
LIBUSB_TRANSFER_CANCELLED
LIBUSB_TRANSFER_CANCELLED
LIBUSB_TRANSFER_CANCELLED
LIBUSB_TRANSFER_CANCELLED
LIBUSB_TRANSFER_CANCELLED
LIBUSB_TRANSFER_CANCELLED
LIBUSB_TRANSFER_CANCELLED
LIBUSB_TRANSFER_CANCELLED
exit thread!
段错误

虽然可以保存一次采集的bin文件，但由于报错无法进行程序中后续采集的控制，想咨询一下这个“void stopRippingBinFile()”函数有什么关系吗？应该如何解决自行“停止翻录bin”的问题？谢谢！
我的控制脚本如下：

data_path1 = "/home/ubuntu/桌面/PyCeleX5-main/data/event6.bin"
data_path2 = "/home/ubuntu/桌面/PyCeleX5-main/data/event7.bin"

def recordEI(root):
   data_path = root
   celex5 = PyCeleX5.PyCeleX5(debug=True)
   celex5.openSensor(PyCeleX5.DeviceType.CeleX5_MIPI)
   celex5.isSensorReady()
   celex5.getClockRate()
   celex5.getEventFrameTime()
   celex5.getOpticalFlowFrameTime()
   celex5.getThreshold()
   celex5.getBrightness()
   celex5.getEventDataFormat()

   # celex5.setSensorFixedMode(PyCeleX5.CeleX5Mode.Event_Off_Pixel_Timestamp_Mode)
   celex5.setSensorFixedMode(PyCeleX5.CeleX5Mode.Event_Intensity_Mode)

   # recoding
   celex5.startRecording(data_path)
   time.sleep(10)
   celex5.stopRecording()

recordEI(data_path1)
# recordEI(data_path2)

**Comment by Aces2017** [comment]
`data_path1 = "/home/ubuntu/桌面/PyCeleX5-main/data/event6.bin"
data_path2 = "/home/ubuntu/桌面/PyCeleX5-main/data/event7.bin"

def recordEI(root):
   data_path = root
   celex5 = PyCeleX5.PyCeleX5(debug=True)
   celex5.openSensor(PyCeleX5.DeviceType.CeleX5_MIPI)
   celex5.isSensorReady()
   celex5.getClockRate()
   celex5.getEventFrameTime()
   celex5.getOpticalFlowFrameTime()
   celex5.getThreshold()
   celex5.getBrightness()
   celex5.getEventDataFormat()

   celex5.setSensorFixedMode(PyCeleX5.CeleX5Mode.Event_Intensity_Mode)

   celex5.startRecording(data_path)
   time.sleep(10)
   celex5.stopRecording()

recordEI(data_path1)
recordEI(data_path2)`

**Comment by kuretru** [comment]
```
celex5 = PyCeleX5.PyCeleX5(debug=True)
celex5.openSensor(PyCeleX5.DeviceType.CeleX5_MIPI)
celex5.isSensorReady()
celex5.getClockRate()
celex5.getEventFrameTime()
celex5.getOpticalFlowFrameTime()
celex5.getThreshold()
celex5.getBrightness()
celex5.getEventDataFormat()
celex5.setSensorFixedMode(PyCeleX5.CeleX5Mode.Event_Intensity_Mode)


def recordEI(root):
    data_path = root
    celex5.startRecording(data_path)
    time.sleep(10)
    celex5.stopRecording()


recordEI(data_path1)
recordEI(data_path2)`
```

**Comment by Aces2017** [comment]
谢谢，已将celex5的设置放在录制函数外，并测试验证 解决了问题，感谢！
    同时想咨询一下，虽然实现了若干段事件流数据的录制，但最后一段数据依然会报错：PyCeleX5.stopRippingBinFile(): already stop ripping bin file 段错误，这个和PyCeleX5中哪个函数的设置有关吗？
    不太明白为什么会自动执行“停止翻录”函数。因后续希望编程实现程序控制bin2csv导出数据，所以问一下潜在的这个问题，谢谢！
