### ISSUE TITLE
demo.py中无法import PyCeleX5

### ISSUE THREAD

**Issue by SamWang-llm** [kuretru/PyCeleX5#4]
在按照readme步骤build 项目之后，结果如下图所示，但是打开demo.py还是无法导入PyCeleX5？
![image](https://github.com/CDEHP-Dataset/PyCeleX5/assets/113619351/e9cfbc72-2e75-4d7e-a974-468d0d41fd1b)
build文件夹内容如下：
![image](https://github.com/CDEHP-Dataset/PyCeleX5/assets/113619351/4c12d387-a236-4520-87c0-c563e38ddc05)

**Comment by kuretru** [comment]
> Make sure the following files exist in the same directory:
>
> * PyCeleX5.cp310-win_amd64.pyd: Compiled in the previous step, located in PyCeleX5\build\Release
> * CeleX.dll: from CelePixel [official SDK](https://github.com/CelePixel/CeleX5-MIPI/tree/master/API/lib/Windows/x64/release)，located in API\lib\Windows\x64\release
> * opencv_world330.dll：from [OpenCV](https://github.com/opencv/opencv/releases/tag/3.3.0)，located in opencv\build\x64\vc14\bin
> * libusb-1.0.dll：from [libusb](https://github.com/libusb/libusb)，located in VS2015-x64\dll\libusb-1.0.dll

都在了吗？报错信息呢？

**Comment by SamWang-llm** [comment]
都在一个文件里面：
![image](https://github.com/CDEHP-Dataset/PyCeleX5/assets/113619351/eae359d0-efa9-4d84-b727-dce729c64457)
报错：
![image](https://github.com/CDEHP-Dataset/PyCeleX5/assets/113619351/4fef730d-015e-434d-8ca1-3b5e589cd9fc)

**Comment by kuretru** [comment]
`from build import PyCeleX5` -> 
```shell
.
| - demo.py
| - build
    | - PyCeleX5.cp310-win_amd64.pyd
    | - CeleX.dll
    | - opencv_world330.dll
    | - libusb-1.0.dll
```

**Comment by SamWang-llm** [comment]
这个demo.sh文件是在哪个文件夹下呢？可以详细说一下吗

**Comment by SamWang-llm** [comment]
以上4个文件已经全部复制到build文件夹下，报错如下：
![image](https://github.com/CDEHP-Dataset/PyCeleX5/assets/113619351/cf228584-92f3-47ac-b0d8-bbc38efcf0a8)

**Comment by kuretru** [comment]
> If there is still problem like ImportError: DLL load failed while importing PyCeleX5: 找不到指定的模块。, please use [Dependencies](https://github.com/lucasg/Dependencies) to find missing dependencies.
