### ISSUE TITLE
Windows系统下使用Dependencies导入哪个文件查看所依赖的库

### ISSUE THREAD

**Issue by 10148pzf** [kuretru/PyCeleX5#5]
请问Windows系统下使用Dependencies导入哪个文件查看所依赖的库？试过libCeleX.so和celex.lib都无法导入Dependencies，仅支持.dll和.exe文件

**Comment by kuretru** [comment]
`PyCeleX5.*-win_amd64.pyd`

**Comment by 10148pzf** [comment]
导入成功了。缺少CeleX.dll：位于API\lib\Windows\x64\release。可是我下载过官方SDK呀，应当将整个API文件夹置于何处？

**Comment by kuretru** [comment]
> Make sure the following files exist in the same directory

**Comment by 10148pzf** [comment]
CeleX.dll在这个目录，甚至直接复制到build文件夹，也是识别不到，是怎么回事呢
![1697513593584](https://github.com/CDEHP-Dataset/PyCeleX5/assets/95392620/17cf453d-a6a3-42bd-ac44-af77e66f31ee)
![1697513634012](https://github.com/CDEHP-Dataset/PyCeleX5/assets/95392620/2b43507f-dd25-40f1-9afe-734a5dfeb1af)

**Comment by kuretru** [comment]
https://github.com/CDEHP-Dataset/PyCeleX5/issues/4#issuecomment-1707891800
